version: '3.8'

services:
  ai-pen-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development

